baseurl = "/"
title = "Blind3y3Design"
author = "Adam Sedwick"
canonifyurls = true
languagecode = "en-us"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Blibd3y3Design | Front-End Architect"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Projects"
    url  = "/projects"
[[menu.main]]
    name = "Resume"
    url  = "/resume"
